"""
LLM-generated questions and student-question assignments.

GeneratedQuestion          — a question produced by the LLM from reference material.
StudentQuestionAssignment  — maps a specific question to a specific student for a task.
"""

import uuid

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Enum,
    ForeignKey,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from .base import Base, SoftDeleteMixin, TimestampMixin

question_difficulty = Enum(
    "easy", "medium", "hard",
    name="question_difficulty",
)


class GeneratedQuestion(TimestampMixin, SoftDeleteMixin, Base):
    """
    A question generated by the LLM from reference corpus paragraphs.

    difficulty  : easy / medium / hard
    bloom_level : Bloom's taxonomy level (Remember, Understand, Apply, etc.)
    is_selected : professor marks which questions to include in distribution
    """

    __tablename__ = "generated_questions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    task_id = Column(
        UUID(as_uuid=True),
        ForeignKey("assignment_tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    question_text = Column(Text, nullable=False)
    difficulty = Column(question_difficulty, nullable=False)
    bloom_level = Column(String(50), nullable=False)
    is_selected = Column(Boolean, default=False, nullable=False)

    task = relationship("AssignmentTask")
    student_assignments = relationship(
        "StudentQuestionAssignment",
        back_populates="question",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return (
            f"<GeneratedQuestion id={self.id} difficulty={self.difficulty} "
            f"bloom={self.bloom_level}>"
        )


class StudentQuestionAssignment(TimestampMixin, Base):
    """
    Maps a generated question to a student for a specific task.

    UniqueConstraint on (student_id, question_id) prevents duplicate assignments.
    """

    __tablename__ = "student_question_assignments"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    student_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    question_id = Column(
        UUID(as_uuid=True),
        ForeignKey("generated_questions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    task_id = Column(
        UUID(as_uuid=True),
        ForeignKey("assignment_tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    __table_args__ = (
        UniqueConstraint(
            "student_id", "question_id",
            name="uq_student_question_no_duplicate",
        ),
    )

    student = relationship("User")
    question = relationship("GeneratedQuestion", back_populates="student_assignments")
    task = relationship("AssignmentTask")

    def __repr__(self) -> str:
        return (
            f"<StudentQuestionAssignment student={self.student_id} "
            f"question={self.question_id}>"
        )
